# Site settings
title: Franklin Maciel
# email: raio.frontendizador@gmail.com
description: >
  Blog de Franklin Maciel
baseurl: ""
url: "http://www.franklinmaciel.com.br"
twitter_username: raiofront
github_username:  teles
author_name: Franklin Maciel
facebook_username: franklinmaciel

# ids for third party scripts
hotjar_id: 64233
google_analytics_id: UA-
disqus_shortname: franklinmaciel

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
paginate: 10
permalink: /:title
paginate_path: "/pagina/:num/"
exclude:
  - 'bower_components/**/*'
  - 'node_modules/**/*'
  - 'README.md'
  - 'bower.json'
  - 'package.json'
  - 'Gruntfile.js'
  - 'Gulpfile.js'
  - 'tasks'
